config/routes.rb
Rails.application.routes.draw do
  #list all lojas
  get 'lojas', to: 'lojas#index'

  #show form to create a new loja
  get 'lojas/new', to: 'lojas#new'

  #list one loja
  get 'lojas/:id', to: 'lojas#show', as: 'loja'

  #create a new loja
  post 'lojas', to: 'lojas#create'

  #show form to edit a loja
  get 'lojas/:id/edit', to: 'lojas#edit', as: 'edit_loja'

  #update a loja
  path 'lojas/:id', to: 'lojas#update'

#delete a loja
  delete 'lojas/:id', to: 'lojas#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/loja.rb
class Loja < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lojas_controller.rb
class LojasController < ApplicationController

  def index
    @lojas = Loja.all
  end

  def show
    @loja = Loja.find(params[:id])
  end

  def new
    @loja = Loja.new
  end

  def create
    @loja = Loja.new(loja_params)
    @loja.save
    redirect_to loja_path(@loja)
  end

  def edit
    @loja = Loja.find(params[:id])
  end

  def update
    @loja = Loja.find(params[:id])
    @loja.update(loja_params)
    redirect_to loja_path(@loja)

  end

  def destroy
    @loja = Loja.find(params[:id])
    @loja.destroy
    redirect_to lojas_path
  end

private

def loja_params
  params.require(:loja).permit(:name, :address, :stars)

end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lojas_helper.rb
module LojasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LojasApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lojas/_form.html.erb
<%= form_for loja do |f|  %>
  <%= f.label :name %>
<%= f.text_field :name %>

 <%= f.label :address %>
<%= f.text_field :address %>

 <%= f.label :stars %>
 <%= f.text_field :stars %>

 <%= f.submit %>


<% end %>

app/views/lojas/edit.html.erb
<h1>Edit New Loja</h1>

<%= render 'form', loja: @loja %>

app/views/lojas/index.html.erb
<h1>Index Lojas </h1>


<ul>
<% @lojas.each  do |loja| %>
<li><%= link_to loja.name, loja_path(loja) %></li>
<% end %>
</ul>


<%= link_to 'New Loja', lojas_new_path %>

app/views/lojas/new.html.erb
<h1>Create New Loja</h1>



<%= form_for @loja do |f|  %>
  <%= f.label :name %>
<%= f.text_field :name %>

 <%= f.label :address %>
<%= f.text_field :address %>

 <%= f.label :stars %>
 <%= f.text_field :stars %>

 <%= f.submit %>


<% end %>

app/views/lojas/show.html.erb
<h1>Info of Lojas</h1>


<p>Name: <%= @loja.name %></p>
<p>Address: <%= @loja.address %></p>
<p>Stars: <%= @loja.stars %></p>


<%= link_to 'Edit' edit_loja_path(@loja) %>


<%=link_to 'Remove this Loja', loja_path, method: :delete %>